//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_ru_RU {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_ru_RU() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Utils.Resources.Localization.Localization_ru_RU", typeof(Localization_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        internal static string AuthorEmpty {
            get {
                return ResourceManager.GetString("AuthorEmpty", resourceCulture);
            }
        }
        
        internal static string NameShort {
            get {
                return ResourceManager.GetString("NameShort", resourceCulture);
            }
        }
        
        internal static string ContentEmpty {
            get {
                return ResourceManager.GetString("ContentEmpty", resourceCulture);
            }
        }
        
        internal static string TitleEmpty {
            get {
                return ResourceManager.GetString("TitleEmpty", resourceCulture);
            }
        }
        
        internal static string TitleLong {
            get {
                return ResourceManager.GetString("TitleLong", resourceCulture);
            }
        }
        
        internal static string TitleShort {
            get {
                return ResourceManager.GetString("TitleShort", resourceCulture);
            }
        }
        
        internal static string AgeEmpty {
            get {
                return ResourceManager.GetString("AgeEmpty", resourceCulture);
            }
        }
        
        internal static string AgeShort {
            get {
                return ResourceManager.GetString("AgeShort", resourceCulture);
            }
        }
        
        internal static string AgeLong {
            get {
                return ResourceManager.GetString("AgeLong", resourceCulture);
            }
        }
        
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
    }
}
